### ISSUE TITLE
Bug(Matching Groups): The number of unmatched befriendees and befrienders fail to update correctly.

### ISSUE THREAD

**Issue by cheeheng** [ShenyiCui/Lions-Rails-6-IssueTicketing#13] opened 2022-06-14 11:06 UTC
## Issue Description (Unexpected Behaviour)
I created a matching group with 1 befriender and 3 befriendees, but upon successfully matching them, the total number of unmatched befrienders and the total number of unmatched befriendees did not decrease, unlike the master branch.

## Expected Behaviour
The total number of unmatched befrienders should decrease from 567 to 566 (first number only), and the total number of unmatched befriendees should decrease from 1190 to 1187.

## Steps to Reproduce the Error
1. From http://localhost:3000/operation/matching_groups, go to 'New matching group'
2. Create matching group called 'testing'
3. Choose region CS3 and set group status to 'Active'.
4. On the search bar below, set Matched to NO and search.
5. For the first three results, click on 'Add to group'.
6. Then, set the 'Search For' to 'Befriender' and click on 'Add to group' for the first result.
7. Click 'Update matching group'.
8. Go back to http://localhost:3000/operation/matching_groups, and observe that the number of unmatched befrienders has not changed.

## Screenshots / Others (Additional context)
The table of the number of unmatched befriendees and the number of unmatched befrienders by region is in http://localhost:3000/operation/matching_groups.

**Comment by ekowidianto** [comment] 2022-06-14 12:40
Root cause:
enum not updated below....
![image](https://user-images.githubusercontent.com/42570513/173579236-dbbddde6-947a-4023-a423-526e296f9cb1.png)

**Comment by ekowidianto** [comment] 2022-06-14 13:50
To check if all enums have been converted

**Comment by ekowidianto** [comment] 2022-06-15 04:46
Fixed in https://gitlab.com/nuscvwo/lions/rails/-/merge_requests/2592/diffs?commit_id=4280f27fb17dd0d510ce98da7465234946891ae2

**Closed as completed** 2022-06-15 05:16 UTC
